$(function() {
    'use strict';
    
///英単語から貼り付け/////////////////////////////////////////////
const words = [
    {en: 'form', ja: '形態'},
    {en: 'research', ja: '研究'},
    {en: 'author', ja: '著者'},
    {en: 'government', ja: '政府'},
    {en: 'society', ja: '社会'},
    {en: 'passage', ja: '(本などの)一節'},
    {en: 'environment', ja: '(自然)環境'},
    {en: 'sense', ja: '感覚'},
    {en: 'case', ja: '場合'},
    {en: 'brain', ja: '脳'},
    {en: 'amount', ja: '量'},
    {en: 'effect', ja: '影響'},
    {en: 'population', ja: '人口'},
    {en: 'technology', ja: '(科学)技術'},
    {en: 'product', ja: '製品'},
    {en: 'nation', ja: '国'},
    {en: 'value', ja: '価値'},
    {en: 'process', ja: '過程'},
    {en: 'community', ja: '地域社会'},
    {en: 'force', ja: '力'},
    {en: 'seem', ja: '～のように見える'},
    {en: 'last', ja: '(ある期間)続く'},
    {en: 'cause', ja: '～を引き起こす'},
    {en: 'face', ja: '～に面する'},
    {en: 'create', ja: '～を作り出す'},
    {en: 'let', ja: '～させる'},
    {en: 'pay', ja: '(～を)支払う'},
    {en: 'produce', ja: '～を生産する'},
    {en: 'allow', ja: '～するのを許す'},
    {en: 'train', ja: '～を訓練する'},
    {en: 'suggest', ja: '～を提案する'},
    {en: 'increase', ja: '増える'},
    {en: 'bear', ja: '～に耐える'},
    {en: 'consider', ja: '～をじっくり考える'},
    {en: 'cost', ja: '(金額・費用)がかかる'},
    {en: 'realize', ja: '(考えて)～に気づく'},
    {en: 'describe', ja: '～の特徴を述べる'},
    {en: 'protect', ja: '～を保護する'},
    {en: 'offer', ja: '～を申し出る'},
    {en: 'tend', ja: '～しがちである'},
    {en: 'following', ja: '次の'},
    {en: 'public', ja: '公共の'},
    {en: 'possible', ja: '(実現)可能な'},
    {en: 'likely', ja: '～しそうだ'},
    {en: 'several', ja: 'いくつかの'},
    {en: 'common', ja: 'よくある'},
    {en: 'individual', ja: '個々の'},
    {en: 'modern', ja: '現代の'},
    {en: 'local', ja: '地元の'},
    {en: 'global', ja: '地球(規模)の'},
    {en: 'moment', ja: '一瞬'},
    {en: 'ability', ja: '能力'},
    {en: 'issue', ja: '問題(点)'},
    {en: 'cell', ja: '細胞'},
    {en: 'species', ja: '(生物学上の)種'},
    {en: 'situation', ja: '状況'},
    {en: 'period', ja: '期間'},
    {en: 'condition', ja: '(物の)状態'},
    {en: 'method', ja: '(組織的な)方法'},
    {en: 'base', ja: '土台'},
    {en: 'meaning', ja: '意味'},
    {en: 'lie', ja: 'うそ'},
    {en: 'attention', ja: '注意'},
    {en: 'project', ja: '事業計画'},
    {en: 'rate', ja: '割合'},
    {en: 'service', ja: '(公共の)事業'},
    {en: 'knowledge', ja: '知識'},
    {en: 'influence', ja: '影響'},
    {en: 'theory', ja: '(学)説'},
    {en: 'interest', ja: '興味'},
    {en: 'stress', ja: '～を強調する'},
    {en: 'discover', ja: '～を発見する'},
    {en: 'include', ja: '～を含む'},
    {en: 'claim', ja: '～を主張する'},
    {en: 'lie', ja: '横になる'},
    {en: 'remain', ja: '～のままである'},
    {en: 'provide', ja: '～を提供する'},
    {en: 'avoid', ja: 'を避ける'},
    {en: 'notice', ja: '～に気づく'},
    {en: 'accept', ja: '～を受け入れる'},
    {en: 'improve', ja: '～を改善する'},
    {en: 'fail', ja: '～しそこなう'},
    {en: 'approach', ja: '～に近づく'},
    {en: 'affect', ja: '～に影響を及ぼす'},
    {en: 'design', ja: '～を設計する'},
    {en: 'express', ja: '表現する'},
    {en: 'depend', ja: 'A次第である'},
    {en: 'occur', ja: '起こる'},
    {en: 'argue', ja: '口論する'},
    {en: 'recognize', ja: '〜だとわかる'},
    {en: 'similar', ja: 'よく似た'},
    {en: 'certain', ja: '確信している'},
    {en: 'average', ja: '平均の'},
    {en: 'major', ja: '(比べて)大きな'},
    {en: 'particular', ja: '特定の'},
    {en: 'present', ja: '出席して'},
    {en: 'physical', ja: '身体の'},
    {en: 'cultural', ja: '文化の'},
    {en: 'recent', ja: '最近の'},
    {en: 'complete', ja: '完全な'},
    {en: 'disease', ja: '病気'},
    {en: 'experiment', ja: '実験'},
    {en: 'benefit', ja: '利益'},
    {en: 'record', ja: '記録'},
    {en: 'role', ja: '役割'},
    {en: 'object', ja: '物体'},
    {en: 'growth', ja: '増加'},
    {en: 'event', ja: '(重要な)出来事'},
    {en: 'memory', ja: '記憶(力)'},
    {en: 'effort', ja: '努力'},
    {en: 'skill', ja: '技能'},
    {en: 'survey', ja: '調査'},
    {en: 'choice', ja: '選択'},
    {en: 'economy', ja: '経済'},
    {en: 'relationship', ja: '関係'},
    {en: 'sentence', ja: '文'},
    {en: 'opportunity', ja: '機会'},
    {en: 'model', ja: '手本'},
    {en: 'fear', ja: '恐れ'},
    {en: 'death', ja: '死'},
    {en: 'guess', ja: '～を推測する'},
    {en: 'prepare', ja: '～を準備する'},
    {en: 'develop', ja: '～を発展[発達]させる'},
    {en: 'solve', ja: '～を解決する'},
    {en: 'encourage', ja: '～を励ます'},
    {en: 'expect', ja: '～を予想[予期]する'},
    {en: 'deal', ja: '〜を処理する'},
    {en: 'measure', ja: '(大きさ・量・速さなど)を測る'},
    {en: 'demand', ja: '～を要求する'},
    {en: 'contain', ja: '(容器・本などが)～を含む'},
    {en: 'various', ja: 'さまざまな'},
    {en: 'political', ja: '政治(上)の'},
    {en: 'scientific', ja: '科学の'},
    {en: 'medical', ja: '医学の'},
    {en: 'whole', ja: '全体の'},
    {en: 'serious', ja: '深刻な'},
    {en: 'single', ja: 'たった1つの'},
    {en: 'general', ja: '一般的な'},
    {en: 'total', ja: '総計の'},
    {en: 'necessary', ja: '必要な'},
    {en: 'material', ja: '材料'},
    {en: 'lack', ja: '不足'},
    {en: 'decision', ja: '決定'},
    {en: 'source', ja: ' (物・事の)源'},
    {en: 'risk', ja: '危険(性)'},
    {en: 'bill', ja: '請求書'},
    {en: 'professor', ja: '(大学の)教授'},
    {en: 'diet', ja: '(日常の)食事'},
    {en: 'quality', ja: '質'},
    {en: 'data', ja: 'データ'},
    {en: 'note', ja: 'メモ'},
    {en: 'challenge', ja: '難題'},
    {en: 'function', ja: '機能'},
    {en: 'article', ja: '記事'},
    {en: 'shape', ja: '形'},
    {en: 'middle', ja: '中央'},
    {en: 'goal', ja: '目標'},
    {en: 'image', ja: 'イメージ'},
    {en: 'figure', ja: '数値'},
    {en: 'decade', ja: '10年間'},
    {en: 'exist', ja: '存在する'},
    {en: 'reduce', ja: '(数量・程度など)を減らす'},
    {en: 'gain', ja: '～を得る'},
    {en: 'require', ja: '～を必要とする'},
    {en: 'prove', ja: '～を証明する'},
    {en: 'prevent', ja: '～するのを妨げる'},
    {en: 'compare', ja: '〜と比較する'},
    {en: 'adapt', ja: '～を適合させる'},
    {en: 'conduct', ja: '～を行う'},
    {en: 'prefer', ja: '〜が好きである'},
    {en: 'successful', ja: '成功した'},
    {en: 'due', ja: 'Aが原因で'},
    {en: 'available', ja: '利用できる'},
    {en: 'western', ja: '西洋の'},
    {en: 'personal', ja: '個人の'},
    {en: 'ancient', ja: '古代の'},
    {en: 'used', ja: 'Aに慣れている'},
    {en: 'native', ja: '出生地の'},
    {en: 'daily', ja: '毎日の'},
    {en: 'correct', ja: '正しい'},
    {en: 'generation', ja: '世代 '},
    {en: 'movement', ja: '運動'},
    {en: 'statement', ja: '声明'},
    {en: 'means', ja: '手段'},
    {en: 'expert', ja: '専門家'},
    {en: 'intelligence', ja: '知能'},
    {en: 'stage', ja: '(変化・発展の)段階'},
    {en: 'variety', ja: 'いろいろなA'},
    {en: 'industry', ja: '産業'},
    {en: 'patient', ja: '患者'},
    {en: 'conversation', ja: '会話'},
    {en: 'clothes', ja: '服'},
    {en: 'pressure', ja: '(社会的な)圧力'},
    {en: 'position', ja: '位置'},
    {en: 'degree', ja: '(温度・角度などの)度'},
    {en: 'range', ja: '範囲'},
    {en: 'access', ja: '(場所への)接近(方法)'},
    {en: 'importance', ja: '重要性'},
    {en: 'neighbor', ja: '隣人'},
    {en: 'policy', ja: '政策'},
    {en: 'indicate', ja: '(調査などが)～を示す'},
    {en: 'refer', ja: '〜に言及する'},
    {en: 'manage', ja: '～を経営する'},
    {en: 'focus', ja: '〜を集中させる'},
    {en: 'promote', ja: '～を促進する'},
    {en: 'observe', ja: '～を観察する'},
    {en: 'raise', ja: '(物・料金など)を上げる'},
    {en: 'maintain', ja: '～を維持する'},
    {en: 'search', ja: '(場所など)を捜す'},
    {en: 'discuss', ja: '～について話し合う'},
    {en: 'media', ja: '(マス)メディア'},
    {en: 'factor', ja: '要因'},
    {en: 'distance', ja: '距離'},
    {en: 'standard', ja: '水準'},
    {en: 'volunteer', ja: 'ボランティア'},
    {en: 'resource', ja: '資源'},
    {en: 'customer', ja: '(商店・企業などの)顧客'},
    {en: 'strategy', ja: '戦略'},
    {en: 'region', ja: '(広大な)地域'},
    {en: 'evidence', ja: '証拠'},
    {en: 'according', ja: '〜によれば'},
    {en: 'rather', ja: 'よりもむしろ'},
    {en: 'probably', ja: 'たぶん'},
    {en: 'perhaps', ja: 'ひょっとすると'},
    {en: 'instead', ja: '(その)代わりに'},
    {en: 'especially', ja: '特に'},
    {en: 'simply', ja: '単に'},
    {en: 'therefore', ja: 'それゆえ'},
    {en: 'thus', ja: 'したがって'},
    {en: 'indeed', ja: '本当に'},
    {en: 'exactly', ja: '正確に'},
    {en: 'nearly', ja: 'ほとんど'},
    {en: 'further', ja: 'さらに'},
    {en: 'immediately', ja: 'すぐに'},
    {en: 'forward', ja: '前へ'},
    {en: 'extremely', ja: '極めて'},
    {en: 'eventually', ja: '結局は'},
    {en: 'hardly', ja: 'ほとんど～ない'},
    {en: 'ahead', ja: '前方に[を]'},
    {en: 'highly', ja: '高度に'},
    {en: 'within', ja: '～以内に'},
    {en: 'per', ja: '～につき'},
    {en: 'including', ja: '～を含めて'},
    {en: 'throughout', ja: '～の間ずっと'},
    {en: 'despite', ja: '～にもかかわらず'},
    {en: 'beyond', ja: '～の向こうに'},
    {en: 'except', ja: '～を除いて'},
    {en: 'whether', ja: '～かどうか'},
    {en: 'provided', ja: 'もし～ならば'},
    {en: 'unless', ja: '～でない限り'},
    {en: 'difficulty', ja: '苦労'},
    {en: 'climate', ja: '気候'},
    {en: 'belief', ja: '確信'},
    {en: 'contrast', ja: '対照'},
    {en: 'blood', ja: '血'},
    {en: 'progress', ja: '進歩'},
    {en: 'damage', ja: '損害'},
    {en: 'item', ja: '項目'},
    {en: 'concept', ja: '概念'},
    {en: 'task', ja: '(やるべき)仕事'},
    {en: 'surface', ja: '表面'},
    {en: 'sale', ja: '販売'},
    {en: 'income', ja: '(定期的な)収入'},
    {en: 'habit', ja: '(個人の)習慣'},
    {en: 'account', ja: '報告'},
    {en: 'danger', ja: '危険'},
    {en: 'freedom', ja: '(権利としての)自由'},
    {en: 'aspect', ja: '(物事の)一面'},
    {en: 'loss', ja: '失うこと'},
    {en: 'mass', ja: '大量のA'},
    {en: 'decline', ja: '減少する'},
    {en: 'replace', ja: '～に取って代わる'},
    {en: 'spread', ja: '広まる'},
    {en: 'waste', ja: '～をむだに使う'},
    {en: 'supply', ja: '～に[を]供給する'},
    {en: 'mention', ja: '～に(ついて)言及する'},
    {en: 'survive', ja: '～を生き延びる'},
    {en: 'add', ja: '(～を)加える'},
    {en: 'separate', ja: '～を隔てる'},
    {en: 'serve', ja: '～に(飲食物)を出す'},
    {en: 'regard', ja: '〜とみなす'},
    {en: 'decrease', ja: '減る'},
    {en: 'perform', ja: '～を上演する'},
    {en: 'attend', ja: '(会議など)に出席する'},
    {en: 'achieve', ja: '～を達成する'},
    {en: 'promise', ja: '(～を)約束する'},
    {en: 'connect', ja: '〜につなぐ'},
    {en: 'count', ja: '(～を)数える'},
    {en: 'attract', ja: '(興味など)を引きつける'},
    {en: 'doubt', ja: '～を疑う'},
    {en: 'concerned', ja: '心配している'},
    {en: 'official', ja: '公式の'},
    {en: 'appropriate', ja: '適切な'},
    {en: 'female', ja: '女性の'},
    {en: 'fresh', ja: '新鮮な'},
    {en: 'powerful', ja: '影響力のある'},
    {en: 'familiar', ja: 'よく知られた'},
    {en: 'ordinary', ja: '普通の'},
    {en: 'wild', ja: '野生の'},
    {en: 'fat', ja: '太っている'},
    {en: 'technique', ja: '(専門)技術'},
    {en: 'phrase', ja: '成句'},
    {en: 'advantage', ja: '利点'},
    {en: 'character', ja: '性格'},
    {en: 'gas', ja: '(燃料用の)ガス'},
    {en: 'citizen', ja: '市民'},
    {en: 'truth', ja: '真実'},
    {en: 'percentage', ja: 'パーセント'},
    {en: 'explanation', ja: '説明'},
    {en: 'instance', ja: '例'},
    {en: 'mark', ja: '印'},
    {en: 'pollution', ja: '汚染'},
    {en: 'feature', ja: '特徴'},
    {en: 'trade', ja: '貿易'},
    {en: 'tool', ja: '道具'},
    {en: 'sort', ja: '種類'},
    {en: 'atmosphere', ja: '雰囲気'},
    {en: 'impact', ja: '影響'},
    {en: 'attitude', ja: '態度'},
    {en: 'crowd', ja: '群衆'},
    {en: 'disappear', ja: '姿を消す'},
    {en: 'define', ja: '～を定義する'},
    {en: 'reflect', ja: '(光など)を反射する'},
    {en: 'contribute', ja: '貢献する'},
    {en: 'represent', ja: '～を代表する'},
    {en: 'match', ja: '～に合う'},
    {en: 'exchange', ja: '～を交換する'},
    {en: 'confuse', ja: '～を困惑させる'},
    {en: 'respond', ja: '反応する'},
    {en: 'treat', ja: '～を扱う'},
    {en: 'male', ja: '男性の'},
    {en: 'huge', ja: '(大きさが)巨大な'},
    {en: 'professional', ja: 'プロの'},
    {en: 'essential', ja: '必要不可欠な'},
    {en: 'current', ja: '現在の'},
    {en: 'positive', ja: '前向きな'},
    {en: 'chemical', ja: '化学の'},
    {en: 'comfortable', ja: '快適な'},
    {en: 'central', ja: '中央の'},
    {en: 'negative', ja: '悪い'},
    {en: 'coal', ja: '石炭'},
    {en: 'gene', ja: '遺伝子'},
    {en: 'traffic', ja: '交通(量)'},
    {en: 'reality', ja: '現実'},
    {en: 'happiness', ja: '幸福'},
    {en: 'balance', ja: 'バランス'},
    {en: 'universe', ja: '宇宙'},
    {en: 'factory', ja: '工場'},
    {en: 'muscle', ja: '筋肉'},
    {en: 'audience', ja: '(劇などの)観客'},
    {en: 'cycle', ja: '循環'},
    {en: 'electricity', ja: '電気'},
    {en: 'link', ja: 'つながり'},
    {en: 'cancer', ja: 'がん'},
    {en: 'contact', ja: '連絡'},
    {en: 'favor', ja: '支持'},
    {en: 'career', ja: '職業'},
    {en: 'majority', ja: '(ある集団の)大多数'},
    {en: 'officer', ja: '役人'},
    {en: 'democracy', ja: '民主主義'},
    {en: 'reply', ja: '返事をする'},
    {en: 'involve', ja: '～を伴う'},
    {en: 'press', ja: '～を押す'},
    {en: 'feed', ja: 'にえさをやる'},
    {en: 'suffer', ja: '[病気]を患う'},
    {en: 'organize', ja: '準備[計画]する'},
    {en: 'succeed', ja: '成功する'},
    {en: 'destroy', ja: '～を破壊する'},
    {en: 'appreciate', ja: '～に感謝する'},
    {en: 'identify', ja: '～を確認する'},
    {en: 'worried', ja: '心配している'},
    {en: 'complicated', ja: '複雑な'},
    {en: 'unique', ja: '類まれな'},
    {en: 'mental', ja: '精神の'},
    {en: 'significant', ja: '重大な'},
    {en: 'responsible', ja: '〜に責任がある'},
    {en: 'blank', ja: '空白の'},
    {en: 'private', ja: '私的な'},
    {en: 'extra', ja: '余分の'},
    {en: 'entire', ja: '全体の'},
    {en: 'novel', ja: '(長編)小説'},
    {en: 'series', ja: '一連の'},
    {en: 'stranger', ja: '見知らぬ人'},
    {en: 'section', ja: '区分'},
    {en: 'principle', ja: '主義'},
    {en: 'popularity', ja: '人気'},
    {en: 'conflict', ja: '対立'},
    {en: 'anger', ja: '怒り'},
    {en: 'satellite', ja: '人工衛星'},
    {en: 'emotion', ja: '感情'},
    {en: 'department', ja: '部門'},
    {en: 'poverty', ja: '貧困'},
    {en: 'structure', ja: '構造'},
    {en: 'insect', ja: '虫'},
    {en: 'revolution', ja: '(政治的)革命'},
    {en: 'safety', ja: '安全'},
    {en: 'creature', ja: '生き物'},
    {en: 'content', ja: '容器などの)中身'},
    {en: 'limit', ja: '制限'},
    {en: 'target', ja: '(攻撃などの)標的'},
    {en: 'divide', ja: '～を分ける'},
    {en: 'complain', ja: '不平を言う'},
    {en: 'remove', ja: '～を取り去る'},
    {en: 'bite', ja: '～をかむ'},
    {en: 'examine', ja: '～を調べる'},
    {en: 'score', ja: '(得点)を取る'},
    {en: 'seek', ja: '(答えなど)を探す'},
    {en: 'ignore', ja: '～を無視する'},
    {en: 'attempt', ja: '～を試みる'},
    {en: 'invent', ja: '～を発明する'},
    {en: 'double', ja: '2倍の'},
    {en: 'complex', ja: '複雑な'},
    {en: 'mobile', ja: '移動式の'},
    {en: 'specific', ja: '特定の'},
    {en: 'normal', ja: '標準の'},
    {en: 'aware', ja: '気づいている'},
    {en: 'regular', ja: '規則的な'},
    {en: 'obvious', ja: '明らかな'},
    {en: 'active', ja: '活動的な'},
    {en: 'characteristic', ja: '特有の'},
    {en: 'profit', ja: '利益'},
    {en: 'association', ja: '協会'},
    {en: 'detail', ja: '細部'},
    {en: 'drug', ja: '麻薬'},
    {en: 'device', ja: '装置'},
    {en: 'trust', ja: '信頼'},
    {en: 'dot', ja: '点'},
    {en: 'owner', ja: '所有者'},
    {en: 'immigrant', ja: '移民'},
    {en: 'excuse', ja: '言い訳'},
    {en: 'prize', ja: '賞'},
    {en: 'shock', ja: 'ショック'},
    {en: 'trend', ja: '傾向'},
    {en: 'track', ja: '小道'},
    {en: 'term', ja: '(専門)用語'},
    {en: 'authority', ja: '権威'},
    {en: 'household', ja: '家族'},
    {en: 'luck', ja: '運'},
    {en: 'code', ja: '規定'},
    {en: 'fuel', ja: '燃料'},
    {en: 'release', ja: '～を解き放す'},
    {en: 'tie', ja: '～を結びつける'},
    {en: 'reveal', ja: '～を明らかにする'},
    {en: 'conclude', ja: '～と結論づける'},
    {en: 'assume', ja: '～と思い込む'},
    {en: 'escape', ja: '逃げる'},
    {en: 'demonstrate', ja: '～を論証する'},
    {en: 'participate', ja: '参加する'},
    {en: 'publish', ja: '～を出版する'},
    {en: 'hang', ja: '(絵・服など)を掛ける'},
    {en: 'previous', ja: '(時間・順序が)前の'},
    {en: 'equal', ja: '(数量などが)等しい'},
    {en: 'direct', ja: '直接の'},
    {en: 'nervous', ja: '緊張して'},
    {en: 'suitable', ja: '適した'},
    {en: 'ill', ja: '病気で'},
    {en: 'fair', ja: '適正な'},
    {en: 'potential', ja: '潜在的な'},
    {en: 'unable', ja: '〜することができない'},
    {en: 'tiny', ja: 'とても小さい'},
    {en: 'tradition', ja: '伝統'},
    {en: 'crop', ja: '(農)作物'},
    {en: 'debate', ja: '討論'},
    {en: 'fashion', ja: '流行'},
    {en: 'bone', ja: '骨'},
    {en: 'relative', ja: '親せき'},
    {en: 'consequence', ja: '結果'},
    {en: 'childhood', ja: '子ども時代'},
    {en: 'storm', ja: '嵐'},
    {en: 'block', ja: 'ブロック'},
    {en: 'refuse', ja: '～を断る'},
    {en: 'lay', ja: '～を置く'},
    {en: 'suppose', ja: '～であろうと思う'},
    {en: 'insist', ja: '(～を)主張する'},
    {en: 'relax', ja: 'くつろぐ'},
    {en: 'direct', ja: '(関心など)を向ける'},
    {en: 'judge', ja: '(～を)判断する'},
    {en: 'recall', ja: '～を思い出す'},
    {en: 'repair', ja: '～を修理する'},
    {en: 'predict', ja: '～を予測する'},
    {en: 'gradually', ja: '徐々に'},
    {en: 'somewhere', ja: 'どこかで[に'},
    {en: 'increasingly', ja: 'ますます'},
    {en: 'relatively', ja: '比較的'},
    {en: 'frequently', ja: '頻繁に'},
    {en: 'otherwise', ja: 'そうしないと'},
    {en: 'closely', ja: '密接に'},
    {en: 'slightly', ja: 'わずかに'},
    {en: 'twice', ja: '2度'},
    {en: 'rapidly', ja: '急速に'},
    {en: 'opposite', ja: '～の向かい(側)に'},
    {en: 'worth', ja: '～の価値がある'},
    {en: 'unlike', ja: '～と違って'},
    {en: 'besides', ja: '～のほかに'},
    {en: 'beside', ja: '～のそばに'},
    {en: 'considering', ja: '～を考慮すると'},
    {en: 'concerning', ja: '～に関して(の)'},
    {en: 'beneath', ja: '～の下に[の]'},
    {en: 'whenever', ja: '～するときはいつも'},
    {en: 'whereas', ja: '(その)一方で～'},
    {en: 'president', ja: '大統領'},
    {en: 'painting', ja: '絵画'},
    {en: 'origin', ja: '起源'},
    {en: 'manner', ja: 'やり方'},
    {en: 'desire', ja: '欲望'},
    {en: 'aid', ja: '援助'},
    {en: 'sight', ja: '見ること'},
    {en: 'strength', ja: '力'},
    {en: 'talent', ja: '才能'},
    {en: 'court', ja: '法廷'},
    {en: 'birth', ja: '誕生'},
    {en: 'labor', ja: '労働'},
    {en: 'scale', ja: '規模'},
    {en: 'comment', ja: '見解'},
    {en: 'spite', ja: '〜にもかかわらず'},
    {en: 'basis', ja: '(知識などの)基礎'},
    {en: 'document', ja: '文書'},
    {en: 'staff', ja: '職員'},
    {en: 'pleasure', ja: '楽しみ'},
    {en: 'appearance', ja: '出現'},
    {en: 'regret', ja: '～を後悔する'},
    {en: 'enable', ja: '～するのを可能にする'},
    {en: 'rely', ja: '〜を頼りにする'},
    {en: 'graduate', ja: '卒業する'},
    {en: 'rush', ja: '大急ぎで行く'},
    {en: 'flow', ja: '(液体・気体が)流れる'},
    {en: 'shift', ja: '(位置など)を移す'},
    {en: 'determine', ja: '～を特定する'},
    {en: 'expand', ja: '(～を)拡大する'},
    {en: 'aim', ja: '〜を目指す'},
    {en: 'earn', ja: '(金)を稼ぐ'},
    {en: 'obtain', ja: '～を入手する'},
    {en: 'encounter', ja: '～に直面する'},
    {en: 'import', ja: '～を輸入する'},
    {en: 'strike', ja: '～にぶつかる'},
    {en: 'emerge', ja: '現れる'},
    {en: 'apply', ja: '〜を申し込む'},
    {en: 'pat', ja: 'を軽くたたく'},
    {en: 'adopt', ja: '(方法など)を採用する'},
    {en: 'gather', ja: '集まる'},
    {en: 'terrible', ja: 'ひどい'},
    {en: 'typical', ja: '典型的な'},
    {en: 'convenient', ja: '都合のよい'},
    {en: 'independent', ja: '独立した'},
    {en: 'asleep', ja: '眠って'},
    {en: 'practical', ja: '現実的な'},
    {en: 'engaged', ja: '〜に従事している'},
    {en: 'false', ja: '(情報などが)間違った'},
    {en: 'disappointed', ja: 'がっかりする'},
    {en: 'primary', ja: '第一の'},
    {en: 'status', ja: '地位'},
    {en: 'crime', ja: '犯罪'},
    {en: 'spot', ja: '場所'},
    {en: 'union', ja: '(労働)組合'},
    {en: 'grade', ja: '学年'},
    {en: 'pain', ja: '(肉体的な)痛み'},
    {en: 'desert', ja: '砂漠'},
    {en: 'path', ja: '(小)道'},
    {en: 'employee', ja: '従業員'},
    {en: 'disaster', ja: '災害'},
    {en: 'coast', ja: '海岸'},
    {en: 'instrument', ja: '器具'},
    {en: 'entrance', ja: '入り口'},
    {en: 'clerk', ja: '店員'},
    {en: 'error', ja: '間違い'},
    {en: 'sheet', ja: '1枚の〜'},
    {en: 'unit', ja: '単位'},
    {en: 'vote', ja: '票'},
    {en: 'essay', ja: 'レポート'},
    {en: 'custom', ja: '慣習'},
    {en: 'charge', ja: 'を請求する'},
    {en: 'settle', ja: '～を解決する'},
    {en: 'admire', ja: '～を賞賛する'},
    {en: 'compete', ja: '競争する'},
    {en: 'hide', ja: '～を隠す'},
    {en: 'concentrate', ja: '集中する'},
    {en: 'upset', ja: '～を動揺させる'},
    {en: 'relieve', ja: 'を和らげる'},
    {en: 'blow', ja: '(風が)吹く'},
    {en: 'remind', ja: '〜を思い出させる'},
    {en: 'behave', ja: 'ふるまう'},
    {en: 'bother', ja: '～を悩ませる'},
    {en: 'admit', ja: 'を認める'},
    {en: 'bow', ja: 'おじぎをする'},
    {en: 'delay', ja: '～を遅らせる'},
    {en: 'advance', ja: '進む'},
    {en: 'preserve', ja: '～を保存する'},
    {en: 'appeal', ja: '懇願する'},
    {en: 'display', ja: '～を展示する'},
    {en: 'ban', ja: '～を禁止する'},
    {en: 'accurate', ja: '(情報が)正確な'},
    {en: 'military', ja: '軍(事)の'},
    {en: 'usual', ja: 'いつもの'},
    {en: 'financial', ja: '財政上の'},
    {en: 'calm', ja: '落ち着いた'},
    {en: 'alternative', ja: '代わりの'},
    {en: 'former', ja: '(時間的に)前の'},
    {en: 'thick', ja: '(物が)厚い'},
    {en: 'commercial', ja: '商業の'},
    {en: 'equivalent', ja: '同等の'},
    {en: 'row', ja: '(主に横の)列'},
    {en: 'passenger', ja: '乗客'},
    {en: 'poison', ja: '毒'},
    {en: 'journey', ja: '(長い)旅行'},
    {en: 'confidence', ja: '信頼'},
    {en: 'threat', ja: '脅威'},
    {en: 'channel', ja: '海峡'},
    {en: 'violence', ja: '暴力(行為)'},
    {en: 'earthquake', ja: '地震'},
    {en: 'evolution', ja: '(生物の)進化'},
    {en: 'pace', ja: '速度'},
    {en: 'plenty', ja: 'たくさんのA'},
    {en: 'logic', ja: '論理'},
    {en: 'tourism', ja: '観光(事業)'},
    {en: 'marriage', ja: '結婚(生活)'},
    {en: 'occasion', ja: '(ある特定の)時'},
    {en: 'impression', ja: '印象'},
    {en: 'destination', ja: '目的地'},
    {en: 'credit', ja: '信用'},
    {en: 'element', ja: '要素'},
    {en: 'intend', ja: '～するつもりである'},
    {en: 'belong', ja: '〜のものである'},
    {en: 'afford', ja: '～する余裕がある'},
    {en: 'grant', ja: '〜を聞き入れる'},
    {en: 'locate', ja: '位置する'},
    {en: 'cross', ja: '(～を)横切る'},
    {en: 'employ', ja: '～を雇う'},
    {en: 'stick', ja: '～をはりつける'},
    {en: 'hate', ja: '～をひどく嫌う'},
    {en: 'reserve', ja: 'を予約する'},
    {en: 'wealthy', ja: '裕福な'},
    {en: 'tough', ja: '困難な'},
    {en: 'universal', ja: '世界共通の'},
    {en: 'academic', ja: '学問の'},
    {en: 'honest', ja: '正直な'},
    {en: 'overall', ja: '全体の'},
    {en: 'urban', ja: '都市の'},
    {en: 'broad', ja: '(幅の)広い'},
    {en: 'efficient', ja: '効率的な'},
    {en: 'proud', ja: '誇りに思って'},
    {en: 'spirit', ja: '心'},
    {en: 'arrow', ja: '矢'},
    {en: 'equipment', ja: '装置'},
    {en: 'edge', ja: '端'},
    {en: 'board', ja: '板'},
    {en: 'athlete', ja: '運動選手'},
    {en: 'harm', ja: '害'},
    {en: 'background', ja: '経歴'},
    {en: 'gap', ja: 'すき間'},
    {en: 'root', ja: '根源'},
    {en: 'youth', ja: '若いころ'},
    {en: 'phenomenon', ja: '現象'},
    {en: 'proportion', ja: '割合'},
    {en: 'moral', ja: '道徳'},
    {en: 'extent', ja: '程度'},
    {en: 'mammal', ja: '哺乳動物'},
    {en: 'thought', ja: '考え'},
    {en: 'context', ja: '背景'},
    {en: 'lecture', ja: '講義'},
    {en: 'colleague', ja: '同僚'},
    {en: 'react', ja: '反応する'},
    {en: 'arrange', ja: '手はずを整える'},
    {en: 'launch', ja: '～を開始する'},
    {en: 'struggle', ja: '奮闘する'},
    {en: 'announce', ja: '～を発表する'},
    {en: 'lock', ja: '～にかぎをかける'},
    {en: 'consist', ja: 'Aから成る'},
    {en: 'consume', ja: '～を消費する'},
    {en: 'weigh', ja: '～の重さがある'},
    {en: 'acquire', ja: '(財産など)を得る'},
    {en: 'rare', ja: 'まれな'},
    {en: 'southern', ja: '南の'},
    {en: 'willing', ja: '～する気がある'},
    {en: 'empty', ja: '(容器が)空の'},
    {en: 'vast', ja: '広大な'},
    {en: 'constant', ja: '絶え間ない'},
    {en: 'ideal', ja: '理想的な'},
    {en: 'domestic', ja: '国内の'},
    {en: 'legal', ja: '合法的な'},
    {en: 'ecological', ja: '環境に優しい'},
    {en: 'flavor', ja: '風味'},
    {en: 'conference', ja: '(公式の)会議'},
    {en: 'circumstance', ja: '事情'},
    {en: 'signal', ja: '合図'},
    {en: 'quantity', ja: '量'},
    {en: 'liquid', ja: '液体'},
    {en: 'breath', ja: '息'},
    {en: 'scholarship', ja: '奨学金'},
    {en: 'ancestor', ja: '祖先'},
    {en: 'soil', ja: '土'},
    {en: 'bar', ja: '棒'},
    {en: 'finding', ja: '発見(物)'},
    {en: 'religion', ja: '宗教'},
    {en: 'journal', ja: '専門誌'},
    {en: 'metal', ja: '金属'},
    {en: 'vehicle', ja: '乗り物'},
    {en: 'campaign', ja: '(政治的な)運動'},
    {en: 'stream', ja: '小川'},
    {en: 'bottom', ja: '一番下'},
    {en: 'frame', ja: '枠'},
    {en: 'handle', ja: 'を処理する'},
    {en: 'transport', ja: '～を輸送する'},
    {en: 'purchase', ja: 'を買う'},
    {en: 'recommend', ja: '～を勧める'},
    {en: 'educate', ja: '～を教育する'},
    {en: 'stare', ja: 'じっと見る'},
    {en: 'roll', ja: '転がる'},
    {en: 'arise', ja: '(問題などが)生じる'},
    {en: 'vary', ja: '(相互に)異なる'},
    {en: 'celebrate', ja: '～を祝う'},
    {en: 'widespread', ja: '広範囲に渡る'},
    {en: 'silent', ja: '黙った'},
    {en: 'thin', ja: '(物が)薄い'},
    {en: 'fundamental', ja: '基本的な'},
    {en: 'loud', ja: '(声が)大きい'},
    {en: 'medium', ja: '中位の'},
    {en: 'conscious', ja: '気づいている'},
    {en: 'annual', ja: '1年間の'},
    {en: 'excellent', ja: '優れた'},
    {en: 'enormous', ja: '非常に大きな'},
    {en: 'reject', ja: '～を拒否する'},
    {en: 'establish', ja: '〜を設立する'},
    {en: 'steal', ja: '～を(こっそり)盗む'},
    {en: 'sink', ja: '沈む'},
    {en: 'request', ja: '～を要請する'},
    {en: 'convince', ja: '～に納得させる'},
    {en: 'surround', ja: '囲まれている'},
    {en: 'calculate', ja: 'を計算する'},
    {en: 'criticize', ja: '～を批判する'},
    {en: 'explore', ja: '～を探検する'},
    {en: 'philosophy', ja: '哲学'},
    {en: 'personality', ja: '個性'},
    {en: 'foreigner', ja: '外国人'},
    {en: 'institution', ja: '(社会的な)機関'},
    {en: 'laboratory', ja: '実験室'},
    {en: 'option', ja: '選択(肢)'},
    {en: 'soldier', ja: '兵隊'},
    {en: 'tax', ja: '税金'},
    {en: 'fiction', ja: '(架空の)小説'},
    {en: 'capital', ja: '首都'},
    {en: 'fully', ja: '十分に'},
    {en: 'greatly', ja: '大いに'},
    {en: 'naturally', ja: '当然(ながら)'},
    {en: 'nevertheless', ja: 'それにもかかわらず'},
    {en: 'overseas', ja: '海外で[へ]'},
    {en: 'surely', ja: '確かに'},
    {en: 'rarely', ja: 'めったに～しない'},
    {en: 'mostly', ja: 'たいてい'},
    {en: 'moreover', ja: 'そのうえ'},
    {en: 'furthermore', ja: 'そのうえ'},
    {en: 'minister', ja: '大臣'},
    {en: 'tale', ja: '話'},
    {en: 'battle', ja: '戦闘'},
    {en: 'facility', ja: '設備'},
    {en: 'broadcast', ja: '放送'},
    {en: 'rank', ja: '地位'},
    {en: 'crisis', ja: '危機'},
    {en: 'stuff', ja: '(漠然と)もの'},
    {en: 'reward', ja: '報酬'},
    {en: 'occupation', ja: '職業'},
    {en: 'property', ja: '財産'},
    {en: 'fee', ja: '(参加などの)料金'},
    {en: 'cash', ja: '現金'},
    {en: 'agreement', ja: '協定'},
    {en: 'civilization', ja: '文明'},
    {en: 'version', ja: '(製品などの)型'},
    {en: 'leisure', ja: '余暇'},
    {en: 'enemy', ja: '敵'},
    {en: 'feather', ja: '羽'},
    {en: 'welfare', ja: '福祉'},
    {en: 'deny', ja: '～を否定する'},
    {en: 'annoy', ja: '～をいらいらさせる'},
    {en: 'differ', ja: '異なる'},
    {en: 'repeat', ja: 'を繰り返す'},
    {en: 'expose', ja: '～をさらす'},
    {en: 'estimate', ja: '～を見積もる'},
    {en: 'transfer', ja: 'を移動させる'},
    {en: 'recover', ja: '回復する'},
    {en: 'insult', ja: '～を侮辱する'},
    {en: 'blame', ja: '～を非難する'},
    {en: 'illustrate', ja: '～を説明する'},
    {en: 'disagree', ja: '反対する'},
    {en: 'entertain', ja: '～を楽しませる'},
    {en: 'translate', ja: '～を翻訳する'},
    {en: 'puzzle', ja: '～を困らせる'},
    {en: 'confirm', ja: '～を確かめる'},
    {en: 'specialize', ja: '〜を専門にする'},
    {en: 'dislike', ja: '～を嫌う'},
    {en: 'lift', ja: '～を持ち上げる'},
    {en: 'resist', ja: '～に抵抗する'},
    {en: 'formal', ja: '正式の'},
    {en: 'worldwide', ja: '世界的な'},
    {en: 'pleased', ja: 'うれしい'},
    {en: 'nearby', ja: '近くの'},
    {en: 'remarkable', ja: '注目すべき'},
    {en: 'historical', ja: '歴史の'},
    {en: 'actual', ja: '実際の'},
    {en: 'sensitive', ja: '敏感な'},
    {en: 'firm', ja: '堅い'},
    {en: 'aggressive', ja: '攻撃的な'},
    {en: 'agriculture', ja: '農業'},
    {en: 'trick', ja: '(人をだます)策略'},
    {en: 'scene', ja: '(映画などの)シーン'},
    {en: 'capacity', ja: '容量'},
    {en: 'trap', ja: '(鳥獣用の)わな'},
    {en: 'tail', ja: '尾'},
    {en: 'army', ja: '軍隊'},
    {en: 'foundation', ja: '(物・事の)基礎'},
    {en: 'guy', ja: '(くだけて)やつ'},
    {en: 'literature', ja: '文学(作品)'},
    {en: 'election', ja: '選挙'},
    {en: 'injury', ja: 'けが'},
    {en: 'ceremony', ja: '式(典)'},
    {en: 'era', ja: '時代'},
    {en: 'furniture', ja: '家具'},
    {en: 'dozen', ja: 'ダース'},
    {en: 'architecture', ja: '建築'},
    {en: 'alcohol', ja: 'アルコール飲料'},
    {en: 'mystery', ja: 'なぞ'},
    {en: 'branch', ja: '枝'},
    {en: 'interrupt', ja: '～を中断させる'},
    {en: 'imply', ja: '～を暗示する'},
    {en: 'warn', ja: '～に警告する'},
    {en: 'persuade', ja: '～を説得する'},
    {en: 'adjust', ja: '〜を調整する'},
    {en: 'advise', ja: '～に忠告する'},
    {en: 'overcome', ja: '〜を克服する'},
    {en: 'permit', ja: '(～に)…を許可する'},
    {en: 'shake', ja: '～を振る'},
    {en: 'deliver', ja: '～を配達する'},
    {en: 'cure', ja: '(病気・人)を治す'},
    {en: 'select', ja: '～を(慎重に)選ぶ'},
    {en: 'investigate', ja: '～を調査する'},
    {en: 'chat', ja: '雑談する'},
    {en: 'remark', ja: '～と述べる'},
    {en: 'suspect', ja: '～であろうと思う'},
    {en: 'praise', ja: '～を賞賛する'},
    {en: 'bark', ja: 'ほえる'},
    {en: 'alter', ja: '～を変える'},
    {en: 'commit', ja: '(犯罪など)を犯す'},
    {en: 'narrow', ja: '(幅の)狭い'},
    {en: 'nuclear', ja: '原子力の'},
    {en: 'strict', ja: '厳しい'},
    {en: 'alive', ja: '生きて'},
    {en: 'severe', ja: '深刻な'},
    {en: 'satisfied', ja: '満足している'},
    {en: 'intellectual', ja: '知的な'},
    {en: 'civil', ja: '市民(として)の'},
    {en: 'unexpected', ja: '思いがけない'},
    {en: 'junior', ja: '後輩の'},
    {en: 'label', ja: 'ラベル'},
    {en: 'snack', ja: '(食間の)軽食'},
    {en: 'shame', ja: '恥ずかしさ'},
    {en: 'automobile', ja: '自動車 《主に米》'},
    {en: 'flood', ja: '洪水'},
    {en: 'oxygen', ja: '酸素'},
    {en: 'layer', ja: '層'},
    {en: 'perspective', ja: '視点'},
    {en: 'depression', ja: '不景気'},
    {en: 'adventure', ja: '冒険'},
    {en: 'category', ja: '範ちゅう'},
    {en: 'tragedy', ja: '悲劇(的事件)'},
    {en: 'diversity', ja: '多様性'},
    {en: 'notion', ja: '(漠然とした)考え'},
    {en: 'tribe', ja: '部族'},
    {en: 'sector', ja: '(経済などの)部門'},
    {en: 'joy', ja: '喜び'},
    {en: 'instruction', ja: '指示'},
    {en: 'trial', ja: '裁判'},
    {en: 'theme', ja: '主題'},
    {en: 'lend', ja: '～を貸す'},
    {en: 'analyze', ja: '～を分析する'},
    {en: 'present', ja: '～を贈呈する'},
    {en: 'fold', ja: '～を折りたたむ'},
    {en: 'emphasize', ja: '～を強調する'},
    {en: 'rent', ja: '～を(有料で)借りる'},
    {en: 'construct', ja: '～を建設する'},
    {en: 'protest', ja: '(～に)抗議する'},
    {en: 'owe', ja: '(…に)～の借金がある'},
    {en: 'absorb', ja: '吸収する'},
    {en: 'elderly', ja: '年配の'},
    {en: 'plain', ja: '明らかな'},
    {en: 'rural', ja: '田舎の'},
    {en: 'reasonable', ja: '分別のある'},
    {en: 'stable', ja: '(状態が)安定した'},
    {en: 'helpful', ja: '役に立つ'},
    {en: 'visual', ja: '視覚の'},
    {en: 'surprising', ja: '驚くべき'},
    {en: 'initial', ja: '最初の'},
    {en: 'solar', ja: '太陽の'},
    {en: 'lung', ja: '肺'},
    {en: 'resident', ja: '居住者'},
    {en: 'quarter', ja: '4分の1'},
    {en: 'agent', ja: '代理人'},
    {en: 'chart', ja: '図'},
    {en: 'gravity', ja: '重力'},
    {en: 'investment', ja: '投資'},
    {en: 'length', ja: '長さ'},
    {en: 'arrival', ja: '到着'},
    {en: 'institute', ja: '学会'},
    {en: 'partner', ja: '仲間'},
    {en: 'alarm', ja: '驚き'},
    {en: 'executive', ja: '幹部'},
    {en: 'tip', ja: '(とがったものの)先'},
    {en: 'shortage', ja: '不足'},
    {en: 'lawyer', ja: '弁護士'},
    {en: 'victim', ja: '犠牲者'},
    {en: 'innovation', ja: '革新'},
    {en: 'bay', ja: '(小さい)湾'},
    {en: 'volcano', ja: '火山'},
    {en: 'abandon', ja: '〜を捨てる'},
    {en: 'forecast', ja: '～を予想する'},
    {en: 'disturb', ja: '～をじゃまする'},
    {en: 'declare', ja: '～を宣言する'},
    {en: 'pause', ja: 'ちょっと止まる'},
    {en: 'capture', ja: '～を捕える'},
    {en: 'attach', ja: '〜に付ける'},
    {en: 'pack', ja: 'に荷物を詰める'},
    {en: 'guarantee', ja: '～を保証する'},
    {en: 'imitate', ja: '～をまねる'},
    {en: 'smart', ja: '頭のよい'},
    {en: 'deaf', ja: '耳が聞こえない'},
    {en: 'capable', ja: '〜する能力がある'},
    {en: 'evil', ja: '悪い'},
    {en: 'flat', ja: '平らな'},
    {en: 'chief', ja: '最高位の'},
    {en: 'artificial', ja: '人工の'},
    {en: 'inner', ja: '内側の'},
    {en: 'mere', ja: '単なる'},
    {en: 'contemporary', ja: '現代の'},
    {en: 'fossil', ja: '化石'},
    {en: 'fault', ja: '責任'},
    {en: 'reputation', ja: '評判'},
    {en: 'regulation', ja: '規則'},
    {en: 'debt', ja: '借金'},
    {en: 'route', ja: '経路'},
    {en: 'disorder', ja: '(心身の)不調'},
    {en: 'honor', ja: '名誉'},
    {en: 'ease', ja: '容易さ'},
    {en: 'substance', ja: '物質'},
    {en: 'dye', ja: '～を染める'},
    {en: 'breed', ja: '繁殖する'},
    {en: 'inspire', ja: '～を奮起させる'},
    {en: 'hesitate', ja: 'ためらう'},
    {en: 'collapse', ja: '崩壊する'},
    {en: 'stretch', ja: '～を伸ばす'},
    {en: 'pretend', ja: '～のふりをする'},
    {en: 'melt', ja: '溶ける'},
    {en: 'pose', ja: '(危険など)をもたらす'},
    {en: 'operate', ja: 'を操作する'},
    {en: 'senior', ja: '年上の'},
    {en: 'related', ja: '関係のある'},
    {en: 'dramatic', ja: '劇的な'},
    {en: 'lonely', ja: 'さびしい'},
    {en: 'electronic', ja: '電子(式)の'},
    {en: 'contrary', ja: '反対の'},
    {en: 'scared', ja: '怖がる'},
    {en: 'anxious', ja: '心配して'},
    {en: 'manual', ja: '手動の'},
    {en: 'giant', ja: '巨大な'},
    {en: 'folk', ja: '人々'},
    {en: 'client', ja: '依頼人'},
    {en: 'peak', ja: '絶頂'},
    {en: 'mood', ja: '気分'},
    {en: 'iron', ja: '鉄'},
    {en: 'pole', ja: '(天体の)極'},
    {en: 'entry', ja: '入ること'},
    {en: 'contract', ja: '契約(書)'},
    {en: 'volume', ja: '量'},
    {en: 'lifetime', ja: '一生'},
    {en: 'beat', ja: '(～を)たたく'},
    {en: 'stimulate', ja: '～を刺激する'},
    {en: 'dive', ja: '(水中に)飛び込む'},
    {en: 'ensure', ja: '～を確実にする'},
    {en: 'detect', ja: '～を見つける'},
    {en: 'cancel', ja: '～を取り消す'},
    {en: 'explode', ja: '爆発する'},
    {en: 'export', ja: '～を輸出する'},
    {en: 'accomplish', ja: '～を達成する'},
    {en: 'acknowledge', ja: ' 〜を認める'},
    {en: 'marine', ja: '海の'},
    {en: 'curious', ja: '好奇心の強い'},
    {en: 'pure', ja: '純粋な'},
    {en: 'extraordinary', ja: '並はずれた'},
    {en: 'upper', ja: '上の(方の)'},
    {en: 'precise', ja: '正確な'},
    {en: 'amazing', ja: 'びっくりするような'},
    {en: 'proper', ja: '適切な'},
    {en: 'sufficient', ja: '十分な'},
    {en: 'brief', ja: '短時間の'},
    {en: 'truly', ja: '本当に'},
    {en: 'unfortunately', ja: '残念ながら'},
    {en: 'necessarily', ja: '必ずしも～ない'},
    {en: 'regardless', ja: '〜に関係なく'},
    {en: 'apart', ja: '離れて'},
    {en: 'apparently', ja: 'どうも～らしい'},
    {en: 'badly', ja: 'まずく'},
    {en: 'somewhat', ja: 'やや'},
    {en: 'definitely', ja: '確かに'},
    {en: 'largely', ja: '主に'},
    {en: 'everywhere', ja: 'あらゆる所で'},
    {en: 'deeply', ja: '非常に'},
    {en: 'fairly', ja: 'かなり'},
    {en: 'absolutely', ja: '完全に'},
    {en: 'aside', ja: '脇に'},
    {en: 'somehow', ja: 'どういうわけか'},
    {en: 'partly', ja: '部分的に(は)'},
    {en: 'afterward(s)', ja: 'あとで'},
    {en: 'nowadays', ja: '近ごろ(は)'},
    {en: 'virtually', ja: '実質的に(は)'},
    {en: 'laughter', ja: '笑い'},
    {en: 'shelter', ja: '避難'},
    {en: 'procedure', ja: '手順'},
    {en: 'appointment', ja: '(面会の)約束'},
    {en: 'tone', ja: '口調'},
    {en: 'border', ja: '国境'},
    {en: 'height', ja: '高さ'},
    {en: 'outcome', ja: '結果'},
    {en: 'motion', ja: '運動'},
    {en: 'exit', ja: '出口'},
    {en: 'corporation', ja: '企業'},
    {en: 'conservation', ja: '(文化財の)保護'},
    {en: 'symptom', ja: '(患者の)症状'},
    {en: 'string', ja: 'ひも'},
    {en: 'mission', ja: '使節(団)'},
    {en: 'fellow', ja: '男'},
    {en: 'sample', ja: '見本'},
    {en: 'campus', ja: 'キャンパス'},
    {en: 'wisdom', ja: '知恵'},
    {en: 'statue', ja: '像'},
    {en: 'interpret', ja: '～を解釈する'},
    {en: 'oppose', ja: '～に反対する'},
    {en: 'defend', ja: '(～を)守る'},
    {en: 'eliminate', ja: '～を排除する'},
    {en: 'compose', ja: '～を構成する'},
    {en: 'generate', ja: '～を生み出す'},
    {en: 'command', ja: '～を[に]命令する'},
    {en: 'pour', ja: '～を注ぐ'},
    {en: 'ruin', ja: '～を破滅させる'},
    {en: 'hire', ja: '～を雇う'},
    {en: 'steady', ja: '安定した'},
    {en: 'considerable', ja: 'かなりの'},
    {en: 'polite', ja: '礼儀正しい'},
    {en: 'secure', ja: '安全な'},
    {en: 'blind', ja: '目の見えない'},
    {en: 'remote', ja: '遠く離れた'},
    {en: 'dirty', ja: '汚れた'},
    {en: 'apparent', ja: '明白な'},
    {en: 'pleasant', ja: '楽しい'},
    {en: 'stupid', ja: 'ばかげた'},
    {en: 'continent', ja: '大陸'},
    {en: 'vision', ja: '視力'},
    {en: 'register', ja: '登録(簿)'},
    {en: 'crew', ja: '乗組員'},
    {en: 'shore', ja: '岸'},
    {en: 'fate', ja: '運命'},
    {en: 'biology', ja: '生物学'},
    {en: 'stock', ja: '蓄え'},
    {en: 'hunger', ja: '飢え'},
    {en: 'objective', ja: '目標'},
    {en: 'sweat', ja: '汗'},
    {en: 'infant', ja: '(乳)幼児'},
    {en: 'minority', ja: '少数'},
    {en: 'wheel', ja: '車輪'},
    {en: 'affair', ja: '事務'},
    {en: 'landscape', ja: '風景'},
    {en: 'loan', ja: 'ローン'},
    {en: 'incident', ja: '(小さな)出来事'},
    {en: 'routine', ja: 'いつもすること'},
    {en: 'humanity', ja: '人間性'},
    {en: 'transform', ja: '～を変化させる'},
    {en: 'glance', ja: 'ちらりと見る'},
    {en: 'quit', ja: '(仕事など)をやめる'},
    {en: 'mix', ja: '～を混ぜる'},
    {en: 'combine', ja: '～を組み合わせる'},
    {en: 'extend', ja: '～を拡大する'},
    {en: 'accompany', ja: '～に同行する'},
    {en: 'dig', ja: '(～を)掘る'},
    {en: 'cope', ja: '〜をうまく処理する'},
    {en: 'apologize', ja: '謝罪する'},
    {en: 'visible', ja: '見える'},
    {en: 'crucial', ja: '決定的な'},
    {en: 'numerous', ja: '多数の'},
    {en: 'sudden', ja: '突然の'},
    {en: 'superior', ja: '(他者より)優れた'},
    {en: 'grand', ja: '壮大な'},
    {en: 'eager', ja: '熱望している'},
    {en: 'latter', ja: '後者の'},
    {en: 'solid', ja: '固体の'},
    {en: 'collective', ja: '集団による'},
    {en: 'imagination', ja: '想像力'},
    {en: 'treasure', ja: '財宝'},
    {en: 'obstacle', ja: '障害'},
    {en: 'harmony', ja: '(意見などの)一致'},
    {en: 'myth', ja: '神話'},
    {en: 'transition', ja: '移り変わり'},
    {en: 'barrier', ja: '防壁'},
    {en: 'seed', ja: '種'},
    {en: 'headache', ja: '頭痛'},
    {en: 'sum', ja: '合計'},
    {en: 'opponent', ja: '(試合などの)相手'},
    {en: 'component', ja: '(構成)要素'},
    {en: 'duty', ja: '義務'},
    {en: 'priority', ja: '優先事項'},
    {en: 'psychology', ja: '心理学'},
    {en: 'wage', ja: '賃金'},
    {en: 'core', ja: '中心(部分)'},
    {en: 'mineral', ja: '鉱物'},
    {en: 'shadow', ja: '影'},
    {en: 'genius', ja: '天才'},
    {en: 'exhibit', ja: '～を展示する'},
    {en: 'distinguish', ja: '見分ける'},
    {en: 'yield', ja: 'を産出する'},
    {en: 'fix', ja: '～を固定する'},
    {en: 'possess', ja: '～を所有している'},
    {en: 'inform', ja: '～に通知する'},
    {en: 'evaluate', ja: '～を評価する'},
    {en: 'urge', ja: '～を促す'},
    {en: 'deserve', ja: '～に値する'},
    {en: 'sue', ja: '(～を)告訴する'},
    {en: 'rude', ja: '失礼な'},
    {en: 'absent', ja: '欠席して'},
    {en: 'frightened', ja: 'おびえた'},
    {en: 'internal', ja: '内部の'},
    {en: 'minor', ja: '小さな'},
    {en: 'awake', ja: '目が覚めて'},
    {en: 'exhausted', ja: '疲れ果てた'},
    {en: 'mad', ja: '頭にきて'},
    {en: 'tropical', ja: '熱帯(地方)の'},
    {en: 'prime', ja: '最重要な'},
    {en: 'committee', ja: '委員会'},
    {en: 'sequence', ja: '一連の'},
    {en: 'legend', ja: '伝説'},
    {en: 'review', ja: '再調査'},
    {en: 'justice', ja: '正義'},
    {en: 'crash', ja: '(車などの)衝突'},
    {en: 'ray', ja: '光線'},
    {en: 'budget', ja: '予算'},
    {en: 'tension', ja: '緊張'},
    {en: 'sake', ja: '～の(目的)ために'},
    {en: 'harvest', ja: '収穫'},
    {en: 'salary', ja: '給料'},
    {en: 'nest', ja: '巣'},
    {en: 'zone', ja: '地帯'},
    {en: 'insurance', ja: '保険'},
    {en: 'dispute', ja: '論争'},
    {en: 'summit', ja: '頂上'},
    {en: 'wound', ja: '傷'},
    {en: 'candidate', ja: '(立)候補者'},
    {en: 'load', ja: '積み荷'},
    {en: 'wrap', ja: '～を包む'},
    {en: 'confront', ja: '直面する'},
    {en: 'dominate', ja: '～を支配する'},
    {en: 'arrest', ja: '～を逮捕する'},
    {en: 'reverse', ja: '～を逆にする'},
    {en: 'nod', ja: 'うなずく'},
    {en: 'weaken', ja: '～を弱める'},
    {en: 'float', ja: '浮かぶ'},
    {en: 'sustain', ja: '持続させる'},
    {en: 'sail', ja: '(～を)航海する'},
    {en: 'consistent', ja: '一貫した'},
    {en: 'raw', ja: '生の'},
    {en: 'classic', ja: '典型的な'},
    {en: 'instant', ja: '即座の'},
    {en: 'crazy', ja: '正気でない'},
    {en: 'reluctant', ja: '～したがらない'},
    {en: 'peaceful', ja: '平和な'},
    {en: 'outdoor', ja: '野外の'},
    {en: 'ethical', ja: '道徳上の'},
    {en: 'precious', ja: '貴重な'},
    {en: 'cattle', ja: '畜牛'},
    {en: 'luxury', ja: 'ぜいたく'},
    {en: 'valley', ja: '谷'},
    {en: 'fund', ja: '基金'},
    {en: 'cough', ja: 'せき(払い)'},
    {en: 'virus', ja: 'ウイルス'},
    {en: 'tongue', ja: '舌'},
    {en: 'prejudice', ja: '偏見'},
    {en: 'emergency', ja: '緊急(事態)'},
    {en: 'delight', ja: '大喜び'},
    {en: 'discourage', ja: '～を落胆させる'},
    {en: 'scream', ja: '悲鳴をあげる'},
    {en: 'resolve', ja: '～を解決する'},
    {en: 'trace', ja: '〜を明らかにする'},
    {en: 'fulfill', ja: '(約束など)を果たす'},
    {en: 'hunt', ja: '～を狩る'},
    {en: 'heal', ja: '治る'},
    {en: 'rid', ja: '取り除く'},
    {en: 'inherit', ja: '～を相続する'},
    {en: 'attribute', ja: '〜のせいにする'},
    {en: 'mild', ja: '温暖な'},
    {en: 'extinct', ja: '絶滅した'},
    {en: 'underground', ja: '地下の'},
    {en: 'smooth', ja: 'なめらかな'},
    {en: 'wise', ja: '賢明な'},
    {en: 'rough', ja: 'でこぼこの'},
    {en: 'ethnic', ja: '民族の'},
    {en: 'permanent', ja: '永久的な'},
    {en: 'neat', ja: 'きちんとした'},
    {en: 'wooden', ja: '木製の'},
    {en: 'restriction', ja: '制限'},
    {en: 'fever', ja: '熱'},
    {en: 'dust', ja: 'ほこり'},
    {en: 'grain', ja: '穀物'},
    {en: 'gender', ja: '性(差)'},
    {en: 'award', ja: '賞'},
    {en: 'humor', ja: 'ユーモア'},
    {en: 'excitement', ja: '興奮(状態)'},
    {en: 'enthusiasm', ja: '熱意'},
    {en: 'convention', ja: '(定期的な)大会'},
    {en: 'pursue', ja: '(目的)を追求する'},
    {en: 'retain', ja: '～を保持する'},
    {en: 'pronounce', ja: '～を発音する'},
    {en: 'endure', ja: '耐える'},
    {en: 'punish', ja: '～を罰する'},
    {en: 'scratch', ja: '～を(爪などで)かく'},
    {en: 'wander', ja: '歩き回る'},
    {en: 'shoot', ja: '(～を)撃つ'},
    {en: 'bury', ja: '埋める'},
    {en: 'consult', ja: '(専門家)に相談する'},
    {en: 'bare', ja: 'むき出しの'},
    {en: 'abstract', ja: '抽象的な'},
    {en: 'mature', ja: '成熟した'},
    {en: 'alike', ja: '似ている'},
    {en: 'innocent', ja: '無罪の'},
    {en: 'modest', ja: '謙虚な'},
    {en: 'intense', ja: '(光などが)強烈な'},
    {en: 'awful', ja: 'ひどい'},
    {en: 'urgent', ja: '緊急の'},
    {en: 'loose', ja: '(結び目が)ゆるい'},
    {en: 'colony', ja: '植民地'},
    {en: 'railroad', ja: '鉄道'},
    {en: 'commitment', ja: '約束'},
    {en: 'sacrifice', ja: '犠牲'},
    {en: 'ceiling', ja: '天井'},
    {en: 'garbage', ja: 'ごみ'},
    {en: 'weapon', ja: '兵器'},
    {en: 'invasion', ja: '侵入'},
    {en: 'fare', ja: '(交通機関の)料金'},
    {en: 'territory', ja: '領土'},
    {en: 'bet', ja: '～を賭ける'},
    {en: 'dismiss', ja: '(提案を)を退ける'},
    {en: 'submit', ja: '～を提出する'},
    {en: 'divorce', ja: '～と離婚する'},
    {en: 'convey', ja: '(感情など)を伝える'},
    {en: 'burst', ja: '破裂する'},
    {en: 'guard', ja: '～を守る'},
    {en: 'swallow', ja: '飲み込む'},
    {en: 'manufacture', ja: '～を生産する'},
    {en: 'convert', ja: '〜に変える'},
    {en: 'vital', ja: '不可欠な'},
    {en: 'odd', ja: '奇妙な'},
    {en: 'primitive', ja: '原始的な'},
    {en: 'flexible', ja: '(計画が)柔軟な'},
    {en: 'uneasy', ja: '不安な'},
    {en: 'prompt', ja: '迅速な'},
    {en: 'distinct', ja: '別個の'},
    {en: 'pale', ja: '(顔が)青白い'},
    {en: 'clever', ja: '頭のよい'},
    {en: 'fluent', ja: '流ちょうな'},
    {en: 'meanwhile', ja: 'その間(に)'},
    {en: 'seldom', ja: 'めったに～しない'},
    {en: 'approximately', ja: 'おおよそ'},
    {en: 'literally', ja: '文字どおりに'},
    {en: 'barely', ja: 'かろうじて'},
    {en: 'forever', ja: '永遠に'},
    {en: 'lately', ja: '最近'},
    {en: 'altogether', ja: 'まったく'},
    {en: 'namely', ja: 'すなわち'},
    {en: 'upstairs', ja: '階上へ[で]'},
    {en: 'burden', ja: '(精神的な)重荷'},
    {en: 'discrimination', ja: '差別(待遇)'},
    {en: 'heritage', ja: '(文化的な)遺産'},
    {en: 'discipline', ja: '訓練'},
    {en: 'dawn', ja: '夜明け'},
    {en: 'steam', ja: '(水)蒸気'},
    {en: 'boundary', ja: '境界(線)'},
    {en: 'scheme', ja: '(政府による)計画'},
    {en: 'fortune', ja: '富'},
    {en: 'abuse', ja: '乱用'},
    {en: 'witness', ja: '目撃者'},
    {en: 'expense', ja: '費用'},
    {en: 'depth', ja: '深さ'},
    {en: 'pile', ja: '(積み上げた)山'},
    {en: 'reform', ja: '(制度の)改革'},
    {en: 'prospect', ja: '(成功の)見込み'},
    {en: 'fame', ja: '名声'},
    {en: 'proof', ja: '証拠'},
    {en: 'compromise', ja: '妥協'},
    {en: 'output', ja: '生産高'},
    {en: 'associate', ja: '結びつけて考える'},
    {en: 'neglect', ja: '～を軽視する'},
    {en: 'bend', ja: '(物が)曲がる'},
    {en: 'vanish', ja: '消える'},
    {en: 'persist', ja: '固執する'},
    {en: 'spoil', ja: '～をだめにする'},
    {en: 'sigh', ja: 'ため息をつく'},
    {en: 'cultivate', ja: '(土地)を耕す'},
    {en: 'perceive', ja: '～に気づく'},
    {en: 'greet', ja: '～にあいさつする'},
    {en: 'assign', ja: '～を割り当てる'},
    {en: 'lean', ja: '傾く'},
    {en: 'cease', ja: '(雨などが)やむ'},
    {en: 'tear', ja: '～を破る'},
    {en: 'gaze', ja: '見つめる'},
    {en: 'cheer', ja: '～を元気づける'},
    {en: 'advertise', ja: '～を宣伝する'},
    {en: 'boil', ja: '～を沸かす'},
    {en: 'defeat', ja: '(試合で)～を破る'},
    {en: 'leap', ja: '跳ぶ'},
    {en: 'fond', ja: '大好きである'},
    {en: 'ultimate', ja: '究極の'},
    {en: 'bored', ja: '退屈して'},
    {en: 'principal', ja: '主要な'},
    {en: 'sophisticated', ja: '洗練された'},
    {en: 'concrete', ja: '具体的な'},
    {en: 'passive', ja: '受動的な'},
    {en: 'dull', ja: '退屈な'},
    {en: 'gross', ja: '総計の'},
    {en: 'foolish', ja: '愚かな'},
    {en: 'pioneer', ja: '先駆者'},
    {en: 'secretary', ja: '秘書'},
    {en: 'appetite', ja: '食欲'},
    {en: 'inhabitant', ja: '住民'},
    {en: 'avenue', ja: '大通り'},
    {en: 'clue', ja: '手がかり'},
    {en: 'wheat', ja: '小麦'},
    {en: 'victory', ja: '勝利'},
    {en: 'estate', ja: '財産'},
    {en: 'bond', ja: 'きずな'},
    {en: 'instinct', ja: '本能'},
    {en: 'poll', ja: '投票'},
    {en: 'resort', ja: '保養地'},
    {en: 'companion', ja: '仲間'},
    {en: 'mess', ja: '散らかった状態'},
    {en: 'baggage', ja: '手荷物'},
    {en: 'prison', ja: '刑務所'},
    {en: 'mechanism', ja: '仕組み'},
    {en: 'courage', ja: '勇気'},
    {en: 'sympathy', ja: '同情'},
    {en: 'resemble', ja: '～に似ている'},
    {en: 'constitute', ja: '(集団)を構成する'},
    {en: 'obey', ja: '従う'},
    {en: 'interfere', ja: '干渉する'},
    {en: 'distribute', ja: '～を分配する'},
    {en: 'cooperate', ja: '協力する'},
    {en: 'fascinate', ja: '～を魅了する'},
    {en: 'substitute', ja: '代わりに使う'},
    {en: 'quote', ja: 'を引用する'},
    {en: 'freeze', ja: '凍る'},
    {en: 'overlook', ja: '～を見下ろす'},
    {en: 'whisper', ja: 'ささやく'},
    {en: 'modify', ja: 'を変更する'},
    {en: 'slide', ja: 'すべる'},
    {en: 'offend', ja: '～の気分を害する'},
    {en: 'impose', ja: '[制限など]を〜に課す'},
    {en: 'edit', ja: '～を編集する'},
    {en: 'prohibit', ja: '～するのを禁止する'},
    {en: 'withdraw', ja: '(組織から)退く'},
    {en: 'anticipate', ja: '～を予想する'},
    {en: 'relevant', ja: '(密接に)関連した'},
    {en: 'guilty', ja: '罪を犯した'},
    {en: 'vivid', ja: '鮮明な'},
    {en: 'acid', ja: '酸性の'},
    {en: 'moderate', ja: '穏健な'},
    {en: 'racial', ja: '人種的な'},
    {en: 'awkward', ja: '気まずい'},
    {en: 'prominent', ja: '卓越した'},
    {en: 'generous', ja: '気前のよい'},
    {en: 'ashamed', ja: '恥じている'},
    {en: 'soul', ja: '魂'},
    {en: 'vessel', ja: '(大型の)船'},
    {en: 'quarrel', ja: '口論'},
    {en: 'crack', ja: '割れ目'},
    {en: 'session', ja: '会合'},
    {en: 'portion', ja: '部分'},
    {en: 'pity', ja: '残念なこと'},
    {en: 'faith', ja: '信頼'},
    {en: 'tune', ja: '曲'},
    {en: 'angle', ja: '角度'},
    {en: 'council', ja: '評議会'},
    {en: 'anniversary', ja: '(毎年の)記念日'},
    {en: 'strain', ja: '緊張'},
    {en: 'miracle', ja: '奇跡'},
    {en: 'ambition', ja: '熱望'},
    {en: 'parliament', ja: '議会'},
    {en: 'column', ja: '(建物の)柱'},
    {en: 'faculty', ja: '(大学の)学部'},
    {en: 'flag', ja: '旗'},
    {en: 'fog', ja: '霧'},
    {en: 'assist', ja: '～を助ける'},
    {en: 'forbid', ja: '～を禁じる'},
    {en: 'propose', ja: '～を提案する'},
    {en: 'rescue', ja: '～を救出する'},
    {en: 'chase', ja: '～を追いかける'},
    {en: 'devote', ja: '〜をささげる'},
    {en: 'assure', ja: '～に保証する'},
    {en: 'rub', ja: '～をこする'},
    {en: 'fade', ja: '見えなくなる'},
    {en: 'polish', ja: '～を磨く'},
    {en: 'silly', ja: '愚かな'},
    {en: 'tight', ja: 'きつい'},
    {en: 'elegant', ja: '上品な'},
    {en: 'gentle', ja: '優しい'},
    {en: 'adequate', ja: '十分な'},
    {en: 'continuous', ja: '絶え間ない'},
    {en: 'brave', ja: '勇敢な'},
    {en: 'jealous', ja: 'ねたんで'},
    {en: 'incredible', ja: '信じられない'},
    {en: 'lazy', ja: '怠け者の'},
    {en: 'unity', ja: '統一'},
    {en: 'murder', ja: '殺人'},
    {en: 'fantasy', ja: '空想'},
    {en: 'harbor', ja: '港'},
    {en: 'funeral', ja: '葬式'},
    {en: 'organ', ja: '(動植物の)器官'},
    {en: 'geography', ja: '地理'},
    {en: 'passion', ja: '情熱'},
    {en: 'sorrow', ja: '(深い)悲しみ'},
    {en: 'excess', ja: '超過'},
    {en: 'frustrate', ja: '(欲求)不満にさせる'},
    {en: 'spill', ja: '～をこぼす'},
    {en: 'exceed', ja: '～を超える'},
    {en: 'restore', ja: '～を回復させる'},
    {en: 'squeeze', ja: '～を絞る'},
    {en: 'stir', ja: '(液体)をかき混ぜる'},
    {en: 'wipe', ja: '(表面)をふく'},
    {en: 'infect', ja: '～に感染させる'},
    {en: 'bathe', ja: '入浴する'},
    {en: 'shrink', ja: '縮む'},
    {en: 'sensible', ja: '賢明な'},
    {en: 'frank', ja: '率直な'},
    {en: 'maximum', ja: '最大の'},
    {en: 'miserable', ja: 'みじめな'},
    {en: 'mutual', ja: '相互の'},
    {en: 'useless', ja: '役に立たない'},
    {en: 'genuine', ja: '本物の'},
    {en: 'grateful', ja: '感謝する'},
    {en: 'spare', ja: '余分の'},
    {en: 'tremendous', ja: 'ものすごい'},
    {en: 'district', ja: '地域'},
    {en: 'voyage', ja: '船旅'},
    {en: 'affection', ja: '愛情'},
    {en: 'virtue', ja: '(美)徳'},
    {en: 'phase', ja: '(変化の)段階'},
    {en: 'blossom', ja: '(果樹の)花'},
    {en: 'merit', ja: '長所'},
    {en: 'slave', ja: '奴隷'},
    {en: 'horror', ja: '恐怖'},
    {en: 'illusion', ja: '幻想'},
    {en: 'approve', ja: '賛成する'},
    {en: 'assemble', ja: '集まる'},
    {en: 'decorate', ja: '～を飾る'},
    {en: 'dare', ja: 'あえて～する'},
    {en: 'prevail', ja: '普及している'},
    {en: 'grasp', ja: '～を握る'},
    {en: 'seize', ja: '～を(ぐいと)つかむ'},
    {en: 'misunderstand', ja: '～を誤解する'},
    {en: 'confess', ja: '～を告白する'},
    {en: 'conquer', ja: '～を征服する'},
    {en: 'sore', ja: '痛い'},
    {en: 'bitter', ja: 'つらい'},
    {en: 'peculiar', ja: '特有の'},
    {en: 'inevitable', ja: '避けられない'},
    {en: 'conservative', ja: '保守的な'},
    {en: 'cruel', ja: '残酷な'},
    {en: 'careless', ja: '不注意な'},
    {en: 'faint', ja: 'かすかな'},
    {en: 'overwhelming', ja: '圧倒的な'},
    {en: 'selfish', ja: 'わがままな'},
    {en: 'republic', ja: '共和国'},
    {en: 'enterprise', ja: '企業'},
    {en: 'despair', ja: '絶望'},
    {en: 'privilege', ja: '特権'},
    {en: 'liberty', ja: '(束縛からの)自由'},
    {en: 'machinery', ja: '機械(類)'},
    {en: 'dignity', ja: '威厳'},
    {en: 'motive', ja: '動機'},
    {en: 'rumor', ja: 'うわさ'},
    {en: 'impulse', ja: '衝動'},
    {en: 'cheat', ja: '～をだます'},
    {en: 'postpone', ja: '～を延期する'},
    {en: 'monitor', ja: '監視する'},
    {en: 'proceed', ja: '続ける'},
    {en: 'retire', ja: '(定年で)退職する'},
    {en: 'negotiate', ja: '交渉する'},
    {en: 'oblige', ja: '～を義務づける'},
    {en: 'boast', ja: '自慢する'},
    {en: 'pray', ja: '祈る'},
    {en: 'starve', ja: '餓える'},
    {en: 'random', ja: '無作為の'},
    {en: 'radical', ja: '根本的な'},
    {en: 'alert', ja: '油断のない'},
    {en: 'outstanding', ja: '目立った'},
    {en: 'ugly', ja: '(外見が)醜い'},
    {en: 'temporary', ja: '一時的な'},
    {en: 'fierce', ja: '激しい'},
    {en: 'vague', ja: 'あいまいな'},
    {en: 'sacred', ja: '神聖な'},
    {en: 'imaginary', ja: '想像上の'},
    {en: 'suburb', ja: '郊外'},
    {en: 'acquaintance', ja: '知り合い'},
    {en: 'charm', ja: '魅力'},
    {en: 'departure', ja: '出発'},
    {en: 'congress', ja: '議会'},
    {en: 'constitution', ja: '憲法'},
    {en: 'suicide', ja: '自殺'},
    {en: 'caution', ja: '用心'},
    {en: 'treaty', ja: '条約'},
    {en: 'pension', ja: '年金'},
    {en: 'multiply', ja: '(大幅に)増やす'},
    {en: 'descend', ja: '降りる'},
    {en: 'rob', ja: '奪う'},
    {en: 'unite', ja: '～を結合させる'},
    {en: 'beg', ja: '～を懇願する'},
    {en: 'omit', ja: '～を除外する'},
    {en: 'suspend', ja: '～を停止する'},
    {en: 'conceal', ja: 'を隠す'},
    {en: 'forgive', ja: '～を許す'},
    {en: 'correspond', ja: '一致する'},
    {en: 'sincere', ja: '誠実な'},
    {en: 'bold', ja: '大胆な'},
    {en: 'parallel', ja: '平行の'},
    {en: 'thorough', ja: '徹底的な'},
    {en: 'supreme', ja: '最高の'},
    {en: 'splendid', ja: 'すばらしい'},
    {en: 'apt', ja: '～しがちである'},
    {en: 'brilliant', ja: 'すばらしい'},
    {en: 'elaborate', ja: '凝った'},
    {en: 'decent', ja: '満足できる'},
];
///////////////////////////////////////////////////////////////

///シャッフル
const shuffle = ([...array]) => {
    for (let i = array.length - 1; i >= 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [array[i], array[j]] = [array[j], array[i]];
    }
    return array;
  }


///初期値/////////////////////

$('#min').val(1);
$('#max').val(Math.ceil(words.length /10));


var min = (eval($('#min').val())-1)*10;
var max = eval($('#max').val())*10;
var minUnit = $('#min').val();
var maxUnit = $('#max').val();
$('h1').text(`Unit${minUnit}〜Unit${maxUnit}`);
var wordsSet = words
var word= wordsSet[min];

$('.mode-btn').click(function(){
    min = (eval($('#min').val())-1)*10;
    max = eval($('#max').val())*10;
    var minUnit = $('#min').val();
    var maxUnit = $('#max').val();
    $('h1').text(`Unit${minUnit}〜Unit${maxUnit}`);

    wordsSet= words.slice(min,max);
    $('.unit-modal-wrapper').css('display','none');

    wordsSet=shuffle(wordsSet);
    word= wordsSet[0]
    $('#card-front').text(word.en);
    $('#card-back').text(word.ja);  
    ansNext();
    i=0;

}
)

$('#re').click(function(){
    $('#mode-set').removeClass('endless');
    $('#mode-set').addClass('nomal');
});

$('#rand-mode').click(function(){
    $('#mode-set').removeClass('nomal');
    $('#mode-set').addClass('endless');
});


///////次の単語
var i = 0;
var ansList = wordsSet.slice().sort(function(){ return Math.random() - 0.5; }).slice(0, 3);
var rand=[0,1,2,3];
ansNext();

function eNext(){
    if($('#mode-set').hasClass('nomal')){
        i = i+1;
        if(i===max){
            if(!alert(ansCount+'門正解')){
                wordsSet=shuffle(wordsSet);
                word= wordsSet[0]
                $('#card-front').text(word.en);
                $('#card-back').text(word.ja);  
                $('#ans1').text(word.ja);
                i=0;
                ansCount=0;
            }
        }else{
            word= wordsSet[i];
        }
    }else if($('#mode-set').hasClass('endless')){
        wordsSet=shuffle(wordsSet);
        word= wordsSet[0];
    } 
    ///もし英語から日本語なら
    if($('#mode').hasClass("en-to-ja")){
        $('#card-front').text(word.en);
        $('#card-back').text(word.ja);  
    }else{
        $('#card-front').text(word.ja);
        $('#card-back').text(word.en);  
    }
}

function ansNext(){
    ansList = wordsSet.slice().sort(function(){ return Math.random() - 0.5; }).slice(0, 3);

    while(ansList.includes(word)){
        ansList = wordsSet.slice().sort(function(){ return Math.random() - 0.5; }).slice(0, 3);
    }
    ansList.push(word);

    rand=shuffle(rand);

    ///英語から日本語なら
    if($('#mode').hasClass("en-to-ja")){
        $('#ans1').text(ansList[rand[0]].ja);
        $('#ans2').text(ansList[rand[1]].ja);
        $('#ans3').text(ansList[rand[2]].ja);
        $('#ans4').text(ansList[rand[3]].ja);
    }else{
        $('#ans1').text(ansList[rand[0]].en);
        $('#ans2').text(ansList[rand[1]].en);
        $('#ans3').text(ansList[rand[2]].en);
        $('#ans4').text(ansList[rand[3]].en);
    }
}


///NEXTボタン
function next(){
    if($('#mode-set').hasClass('nomal')){
        if(i<max-1){
            eNext();
            ansNext();
        }else{
            if(!alert(ansCount+'門正解')){
                wordsSet=shuffle(wordsSet);
                word= wordsSet[0]
                $('#card-front').text(word.en);
                $('#card-back').text(word.ja);  
                $('#ans1').text(word.ja);
                i=0;
                ansCount=0;
            }
        }
    }else{
        eNext();
        ansNext();        
    }

}



///カードめくり（解答が出てるとき）
function enToJa(){
    if($('#card').hasClass('open')){
        $('#card').removeClass('open').delay(600).queue(function(next){
            eNext();
            ansNext();
            $("#card-back").css('background', '#5dca88')
            next();
        });
    }else{
        next();
    }
}

$('#btn').click(function(){
    enToJa();
})


///カード裏返し
function flip(){
    if($('#card').hasClass("open")){
        $('#card').removeClass("open");
    } else{
        $('#card').addClass("open");
    }
}
$('#card').click(flip);



///解答ボタン
$('.ans').click(function(){
    flip();
    if($(this).text()===$('#card-back').text()){
        $("#card-back").css('background', '#ff7474');
        // [ID:sound-file]の音声ファイルを再生[play()]する
	    $('#sound-file1').get(0).play() ;
        // 生回数を数える
        ansCount=ansCount+1;
    }else{
        $("#card-back").css('background', '#2181ff');
        // [ID:sound-file]の音声ファイルを再生[play()]する
	    $('#sound-file2').get(0).play();
        //間違ったリスト
        missList.push(word);
    }
});
var ansCount=0;
var missList=[];

//切り替え
$('#mode').click(function(){
    
    if($('#mode').hasClass("en-to-ja")){
        $('#mode').removeClass("en-to-ja");
        $('#mode').text("日本語→英語");
        $('#card-front').text(word.ja);
        $('#card-back').text(word.en); 
        ansNext();
    } else{
        $('#mode').addClass("en-to-ja");
        $('#mode').text("英語→日本語");
        $('#card-front').text(word.en);
        $('#card-back').text(word.ja);
        ansNext();
    }        
});

$('h1').click(function(){
    $('.unit-modal-wrapper').css('display','block');
});


});
